import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home({ experience, serverTime }) {
  const [clientTime, setClientTime] = useState("");

  useEffect(() => {
    setClientTime(new Date().toISOString());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Petco A/B Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <code style={{ fontSize: "22px" }} className={styles.main}>
        Experience: {experience}
        <br />
        ServerTime: {serverTime}
        <br />
        ClientTime: {clientTime}
        <br />
      </code>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  console.log("==== req.cookies ====\n", req.cookies);

  const experience = req?.cookies?.experience ?? "none";

  return {
    props: { experience, serverTime: new Date().toISOString() },
  };
}
