/*
 * The idea is to make Cloudflare to cache two (or more) versions of
 * the same page. For a regular page with A/B test we would have 2 possible
 * URLs. /page-name and /page-name/b.
 *
 * Cloudflare would have 2 cached pages. It would point to one of each
 * depending on a cookie or if no cookie is set, it will flip a coin to
 * chose one.
 *
 * So already in the server code we have the experience we are in, depending
 * only on the file we are. In the Cloudflare worker we will cache the two
 * pages remove the /b (if we are in experience B) from the URL and set the
 * cookies.
 *
 * Note: unfortunately AWS + serverless does not support Next.js middleware.
 * The solution with it is way more elegant.
 */

import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { brazilTimeString } from "../helpers/brazilTime";
import styles from "../styles/Home.module.css";

export default function Home({ serverTime, nonce }) {
  const [clientTime, setClientTime] = useState("");

  useEffect(() => {
    setClientTime(brazilTimeString());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Petco A/B Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ fontSize: "20px" }} className={styles.main}>
        <div style={{ display: "flex", marginBottom: "16px" }}>
          <Link href="/product">
            <a>product</a>
          </Link>
          <span>&nbsp;|&nbsp;</span>

          <Link href="/product/b">
            <a>product/b</a>
          </Link>
        </div>

        <code>
          Page: Home
          <br />
          ServerTime: {serverTime}
          <br />
          ClientTime: {clientTime}
        </code>

        <p>{nonce}</p>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  console.log("==== Home ====");

  return {
    props: {
      serverTime: brazilTimeString(),
      nonce: Math.floor(Math.random() * 1000000),
    },
  };
}
