import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home({ serverTime }) {
  const [clientTime, setClientTime] = useState("");

  useEffect(() => {
    setClientTime(new Date().toISOString());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Petco A/B Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ fontSize: "22px" }} className={styles.main}>
        <div style={{ display: "flex", marginBottom: "16px" }}>
          <Link href="/product">
            <a>product</a>
          </Link>
          <span>&nbsp;|&nbsp;</span>

          <Link href="/product/a">
            <a>product/a</a>
          </Link>
          <span>&nbsp;|&nbsp;</span>

          <Link href="/product/b">
            <a>product/b</a>
          </Link>
        </div>

        <code>
          Page: Home
          <br />
          ServerTime: {serverTime}
          <br />
          ClientTime: {clientTime}
        </code>
      </main>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  return {
    props: { serverTime: new Date().toISOString() },
  };
}
